### ISSUE TITLE
No Workspace found in Developer Sandbox

### ISSUE THREAD

**Issue by hwirnsberger** [redhat-developer/devspaces-gateway-plugin#70]
Hi :-)

We are currently testing DevSpaces on [Developer Sandbox](https://developers.redhat.com/developer-sandbox)
However, when we try to connect to a running workspace it cannot find one.

How does devspaces-gateway-plugin check which workspaces are available?
Are there spezial permissions needed which we maybe do not have in the sandbox?

Maybe you can try it yourself?

Thx and best regards

**Comment by hwirnsberger** [comment]
Any news? :-)

**Comment by hwirnsberger** [comment]
Also found some Logs in Intellij:

2024-08-13 14:39:08,439 [ 581699]   INFO - STDERR - Exception in thread "Thread-95" io.kubernetes.client.openapi.ApiException: 
2024-08-13 14:39:08,440 [ 581700]   INFO - STDERR - 	at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:973)
2024-08-13 14:39:08,440 [ 581700]   INFO - STDERR - 	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:885)
2024-08-13 14:39:08,440 [ 581700]   INFO - STDERR - 	at io.kubernetes.client.openapi.apis.CustomObjectsApi.listNamespacedCustomObjectWithHttpInfo(CustomObjectsApi.java:4312)
2024-08-13 14:39:08,440 [ 581700]   INFO - STDERR - 	at io.kubernetes.client.openapi.apis.CustomObjectsApi.listNamespacedCustomObject(CustomObjectsApi.java:4185)
2024-08-13 14:39:08,440 [ 581700]   INFO - STDERR - 	at com.redhat.devtools.gateway.openshift.DevWorkspaces.list(DevWorkspaces.kt:35)
2024-08-13 14:39:08,440 [ 581700]   INFO - STDERR - 	at com.redhat.devtools.gateway.view.steps.DevSpacesRemoteServerConnectionStepView.doRefreshAllDevWorkspaces(DevSpacesRemoteServerConnectionStepView.kt:134)
2024-08-13 14:39:08,440 [ 581700]   INFO - STDERR - 	at com.redhat.devtools.gateway.view.steps.DevSpacesRemoteServerConnectionStepView.refreshAllDevWorkspaces$lambda$3(DevSpacesRemoteServerConnectionStepView.kt:109)
2024-08-13 14:39:08,440 [ 581700]   INFO - STDERR - 	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by hwirnsberger** [comment]
So the Situation is the following. We have 2 namespaces in the sandbox. In one we do not have permission to query custom resource devworkspaces.
Adding exception handling should solve that problem:
https://github.com/redhat-developer/devspaces-gateway-plugin/blob/a035cfcfd52aaa8de7ba6bed71e5ca1e33c2bd6a/src/main/kotlin/com/redhat/devtools/gateway/view/steps/DevSpacesRemoteServerConnectionStepView.kt#L139

After that we can select the workspace. but connection still does not work. we get a timeout after 60 seconds

**Comment by azatsarynnyy** [comment]
This should already be fixed in https://github.com/redhat-developer/devspaces-gateway-plugin/pull/134
