### ISSUE TITLE
Unable to connect to Openshift Cluster

### ISSUE THREAD

**Issue by budgester** [redhat-developer/devspaces-gateway-plugin#88]
Logged in with token and am able to list all devspace (cluster admin) 

Non cluster admin can't even see their own workspace.

Try and connect to workspace

```
Remote server connection failed.

java.io.IOException: Projects are not ready after 60 seconds.
	at com.redhat.devtools.gateway.server.RemoteServer.waitProjectsReady(RemoteServer.kt:62)
	at com.redhat.devtools.gateway.DevSpacesConnection.doConnection(DevSpacesConnection.kt:53)
	at com.redhat.devtools.gateway.DevSpacesConnection.connect(DevSpacesConnection.kt:37)
	at com.redhat.devtools.gateway.view.steps.DevSpacesRemoteServerConnectionStepView.connect$lambda$25(DevSpacesRemoteServerConnectionStepView.kt:205)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

Looking for how to debug this.

**Comment by budgester** [comment]
https://github.com/davedaemon/devspaces-gateway-plugin/commit/037879a2c55abef94b0f78aac9425f7800e4bf3c
